# Curated seed sources for GrowthBoss Marketing Council
web:
  # Gary Vaynerchuk
  - https://www.garyvaynerchuk.com/blog/
  - https://www.garyvaynerchuk.com/askgaryvee/
  - https://www.vaynermedia.com/insights/
  - https://www.garyvaynerchuk.com/47-pages-that-will-change-your-entire-marketing-organization-approach/
  - https://www.garyvaynerchuk.com/jab-jab-jab-right-hook/
  
  # Alex Hormozi
  - https://www.alexhormozi.com/writing
  - https://www.acquisition.com/resources
  - https://www.acquisition.com/blog
  - https://www.acquisition.com/podcast
  
  # Iman Gadzhi
  - https://www.imangadzhi.com/blog
  - https://www.imangadzhi.com/videos
  - https://www.imangadzhi.com/resources
  
  # GrowthBoss - Our Agency
  - https://www.growthboss.co/
  - https://www.growthboss.co/services
  - https://www.growthboss.co/about
  - https://www.growthboss.co/case-studies
  - https://www.growthboss.co/blog
  - https://www.growthboss.co/website-development-design
  - https://www.growthboss.co/brand-strategy-identity-design
  - https://www.growthboss.co/seo
  - https://www.growthboss.co/social-performance-email-sms-marketing
  - https://www.growthboss.co/photography-videography
  - https://www.growthboss.co/recruitment-talent-acquisition

youtube:
  # Gary Vee - Key videos
  - https://www.youtube.com/watch?v=Em1UXBOJ4QU  # Blueprint for Winning Business Strategy
  - https://www.youtube.com/watch?v=UqQ2cGsT4yQ
  - https://www.youtube.com/watch?v=3H4l3bG1tF4
  
  # Alex Hormozi - Key videos
  - https://www.youtube.com/watch?v=HMOB8VGd1j8  # $100M Offers
  - https://www.youtube.com/watch?v=8fX2m3QT9Kc  # How to price your product
  - https://www.youtube.com/watch?v=z9hNTJ8FHIk  # The Easiest Way To Get Customers
  
  # Iman Gadzhi - Key videos  
  - https://www.youtube.com/watch?v=nk1JqfS0YKY
  - https://www.youtube.com/watch?v=7tiR7vm4cB8  # Agency Navigator
  - https://www.youtube.com/watch?v=K16Q2E5gN_E  # How to start a marketing agency

notes:
  - Focus on client acquisition, offers, content frameworks, SMMA ops, pricing, lead gen, sales, agency building.
  - Each mentor has unique strengths: Gary (content/social), Hormozi (offers/pricing), Gadzhi (agency ops/SMMA).
